spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password
    ##配置监控统计拦截的filters，去掉后面监控界面sql将无法统计，wall用于防火墙
    filters: stat,wall,log4j
    ##最大活跃数
    maxActive: 20
    ##初始化数量
    initialSize: 1
    ##最大连接等待超时时间
    maxWait: 60000
    ##打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    ##通过connectionProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minldle: 1
    timeBetweenEvictionRunsMills: 60000
    minEvictableldleTimeMills: 300000
    validationQuery: select 1 from dual
    testWhileldle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    format_sql: true
  ##配置redis数据库
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      ##默认是索引为0的数据库
    database: 0
server:
  port: 9090



